import { AllocationStrategy } from '../types';

export const STRATEGY_TEMPLATES: AllocationStrategy[] = [
  {
    mode: 'pro',
    templateName: 'Balanced Aggressive',
    allocations: [
      {
        poolType: 'stablecoin',
        targetPercentage: 30,
        minAPY: 7,
        maxAPY: 15,
        protocols: ['aave-v3-usdc', 'compound-v3-usdc'],
      },
      {
        poolType: 'yield_aggregator',
        targetPercentage: 30,
        minAPY: 20,
        maxAPY: 60,
        protocols: ['beefy-volatile', 'yearn-multi'],
      },
      {
        poolType: 'dex',
        targetPercentage: 25,
        minAPY: 30,
        maxAPY: 100,
        protocols: ['aerodrome-usdc', 'uniswap-v3'],
      },
      {
        poolType: 'staking',
        targetPercentage: 15,
        minAPY: 25,
        maxAPY: 80,
        protocols: ['moonwell-multi', 'seamless-multi'],
      },
    ],
    expectedDailyAPY: { min: 0.1, max: 0.3 },
    expectedYearlyAPY: { min: 30, max: 100 },
    riskLevel: 'High',
    description: 'Well-balanced aggressive strategy with diversified risk across all pool types',
    isCustom: false,
  },
  {
    mode: 'pro',
    templateName: 'Max Yield Focus',
    allocations: [
      {
        poolType: 'yield_aggregator',
        targetPercentage: 70,
        minAPY: 20,
        maxAPY: 80,
        protocols: ['beefy-volatile', 'yearn-multi', 'convex-multi'],
      },
      {
        poolType: 'dex',
        targetPercentage: 20,
        minAPY: 30,
        maxAPY: 120,
        protocols: ['aerodrome-usdc', 'uniswap-v3'],
      },
      {
        poolType: 'stablecoin',
        targetPercentage: 10,
        minAPY: 7,
        maxAPY: 15,
        protocols: ['aave-v3-usdc'],
      },
      {
        poolType: 'staking',
        targetPercentage: 0,
        minAPY: 0,
        maxAPY: 0,
        protocols: [],
      },
    ],
    expectedDailyAPY: { min: 0.15, max: 0.4 },
    expectedYearlyAPY: { min: 50, max: 150 },
    riskLevel: 'High',
    description: 'Maximum yield through aggressive yield aggregators - highest potential returns',
    isCustom: false,
  },
  {
    mode: 'pro',
    templateName: 'DEX Liquidity Master',
    allocations: [
      {
        poolType: 'dex',
        targetPercentage: 50,
        minAPY: 30,
        maxAPY: 120,
        protocols: ['aerodrome-usdc', 'uniswap-v3', 'velodrome-stable'],
      },
      {
        poolType: 'staking',
        targetPercentage: 30,
        minAPY: 25,
        maxAPY: 80,
        protocols: ['moonwell-multi', 'seamless-multi'],
      },
      {
        poolType: 'stablecoin',
        targetPercentage: 20,
        minAPY: 7,
        maxAPY: 15,
        protocols: ['aave-v3-usdc', 'compound-v3-usdc'],
      },
      {
        poolType: 'yield_aggregator',
        targetPercentage: 0,
        minAPY: 0,
        maxAPY: 0,
        protocols: [],
      },
    ],
    expectedDailyAPY: { min: 0.12, max: 0.35 },
    expectedYearlyAPY: { min: 40, max: 120 },
    riskLevel: 'High',
    description: 'Heavy focus on DEX liquidity pools for trading fee income and farming rewards',
    isCustom: false,
  },
  {
    mode: 'pro',
    templateName: 'Staking Powerhouse',
    allocations: [
      {
        poolType: 'staking',
        targetPercentage: 50,
        minAPY: 25,
        maxAPY: 100,
        protocols: ['moonwell-multi', 'seamless-multi', 'aave-staking'],
      },
      {
        poolType: 'yield_aggregator',
        targetPercentage: 30,
        minAPY: 20,
        maxAPY: 60,
        protocols: ['beefy-stable', 'yearn-usdc'],
      },
      {
        poolType: 'stablecoin',
        targetPercentage: 20,
        minAPY: 7,
        maxAPY: 15,
        protocols: ['aave-v3-usdc', 'compound-v3-usdc'],
      },
      {
        poolType: 'dex',
        targetPercentage: 0,
        minAPY: 0,
        maxAPY: 0,
        protocols: [],
      },
    ],
    expectedDailyAPY: { min: 0.11, max: 0.32 },
    expectedYearlyAPY: { min: 35, max: 110 },
    riskLevel: 'High',
    description: 'Maximize staking rewards with protocol governance tokens and revenue sharing',
    isCustom: false,
  },
];
